---
# tasks file for compute-neutron
  - name: Install neutron-linuxbridge-agent on compute node
    apt: name=neutron-linuxbridge-agent state=present force=yes

  - name: Configure DEFAULT section in /etc/neutron/neutron.conf
    ini_file: dest=/etc/neutron/neutron.conf
              section="{{ item.section }}"
              option="{{ item.option }}"
              value="{{ item.value }}"
    with_items:
      - { section: 'DEFAULT', option: 'rpc_backend', value: 'rabbit' }
      - { section: 'oslo_messaging_rabbit', option: 'rabbit_hosts', value: "{% for host in groups['controller_nodes'] %}{{ hostvars[host]['ansible_fqdn' ] }}:5672{% if not loop.last %},{% endif %}{% endfor %}" }
      - { section: 'oslo_messaging_rabbit', option: 'rabbit_userid', value: 'openstack' }
      - { section: 'oslo_messaging_rabbit', option: 'rabbit_password', value: "{{ rabbit_pass }}" }
      - { section: 'DEFAULT', option: 'auth_strategy', value: 'keystone' }
      - { section: 'keystone_authtoken', option: 'auth_uri', value: "http://{{ public_vip_fqdn }}:{{ keystone_public_port }}" }
      - { section: 'keystone_authtoken', option: 'auth_url', value: "http://{{ internal_vip_fqdn }}:{{ keystone_admin_port }}" }
      - { section: 'keystone_authtoken', option: 'memcached_servers', value: "{% for host in groups['controller_nodes'] %}{{ hostvars[host]['ansible_fqdn' ] }}:{{ memcached_port }}{% if not loop.last %},{% endif %}{% endfor %}" }
      - { section: 'keystone_authtoken', option: 'auth_type', value: 'password' }
      - { section: 'keystone_authtoken', option: 'project_domain_name', value: 'default' }
      - { section: 'keystone_authtoken', option: 'user_domain_name', value: 'default' }
      - { section: 'keystone_authtoken', option: 'project_name', value: 'service' }
      - { section: 'keystone_authtoken', option: 'username', value: 'neutron' }
      - { section: 'keystone_authtoken', option: 'password', value: "{{ neutron_user_pass }}" }

  - name: Configure linux_bridge in /etc/neutron/plugins/ml2/linuxbridge_agent.ini
    ini_file: dest=/etc/neutron/plugins/ml2/linuxbridge_agent.ini
              section="{{ item.section }}"
              option="{{ item.option }}"
              value="{{ item.value }}"
    with_items:
      - { section: 'linux_bridge', option: 'physical_interface_mappings', value: "provider:{{ mgmt_iface }}" }
      - { section: 'vxlan', option: 'enable_vxlan', value: 'True' }
      - { section: 'vxlan', option: 'local_ip', value: "{{ hostvars[inventory_hostname]['ansible_'+ mgmt_iface ]['ipv4']['address'] }}" }
      - { section: 'vxlan', option: 'l2_population', value: 'True' }
      - { section: 'securitygroup', option: 'enable_security_group', value: 'True' }
      - { section: 'securitygroup', option: 'firewall_driver', value: "neutron.agent.linux.iptables_firewall.IptablesFirewallDriver" }

  - name: Configure neutron section in /etc/nova/nova.conf
    ini_file: dest=/etc/nova/nova.conf
              section="{{ item.section }}"
              option="{{ item.option }}"
              value="{{ item.value }}"
    with_items:
      - { section: 'neutron', option: 'url', value: "http://{{ internal_vip_fqdn }}:{{ neutron_port }}" }
      - { section: 'neutron', option: 'auth_url', value: "http://{{ internal_vip_fqdn }}:{{ keystone_admin_port }}" }
      - { section: 'neutron', option: 'auth_type', value: 'password' }
      - { section: 'neutron', option: 'project_domain_name', value: 'default' }
      - { section: 'neutron', option: 'user_domain_name', value: 'default' }
      - { section: 'neutron', option: 'region_name', value: 'RegionOne' }
      - { section: 'neutron', option: 'project_name', value: 'service' }
      - { section: 'neutron', option: 'username', value: 'neutron' }
      - { section: 'neutron', option: 'password', value: "{{ neutron_user_pass }}" }

  - name: Restart Nova-compute
    service: name={{ item }} state=restarted
    with_items:
      - nova-compute
      - neutron-linuxbridge-agent
