---
# tasks file for controller-memcached
  - name: Install memcached python-memcache in controller node
    apt: name={{ item }} state=present force=yes
    with_items:
     - memcached
     - python-memcache
    tags: memcached-packages

  - name: Update /etc/memcached
    lineinfile: dest=/etc/memcached.conf
               regexp={{ item.regexp }}
               line={{ item.line }}
               backrefs=yes
    with_items:
      - { regexp: "^-p 11211", line: "-p {{ memcached_port }}" }
      - { regexp: "^-l 127.0.0.1", line: "-l {{ hostvars[inventory_hostname]['ansible_'+ mgmt_iface ]['ipv4']['address'] }}" }

  - name: Restart Memcached
    service: name=memcached state=restarted
